package com.rgpt.pdflib;

/**
 * RGPT Library
 * 
 * This interface is the notification event to report the error in
 * PDFVIewController that is originally generated by the PDF Library
 * 
 * @author Narayan
 * 
 */

public interface PDFErrorReportListener {
	public void reportError(String mesg, Object data);
}
